name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo make bootstrap_lib

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      #- name: Run tests
      #  run: |
      #    cd build
      #    make test  
